# Generated by Django 5.2.14 on 2026-05-25 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('successful_vote_submission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failed_vote_attempt_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duplicate_vote_prevention_count', models.PositiveIntegerField(default=0)),
                ('otp_success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('otp_failure_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('uptime_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], default='operational', max_length=20)),
                ('usability_notes', models.TextField(blank=True)),
                ('reliability_notes', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='elections.election')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_student_id_number', models.CharField(max_length=50)),
                ('attempted_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed_not_found', 'Failed - Student Not Found'), ('failed_ineligible', 'Failed - Not Eligible'), ('failed_already_voted', 'Failed - Already Voted'), ('failed_otp_invalid', 'Failed - OTP Invalid'), ('failed_otp_expired', 'Failed - OTP Expired'), ('failed_otp_exhausted', 'Failed - OTP Attempts Exhausted'), ('duplicate_attempt', 'Duplicate Vote Attempt'), ('election_closed', 'Failed - Election Closed')], max_length=50)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='elections.election')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
