services:
  - type: web
    name: univote-web
    env: python
    rootDir: univote
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn univote_config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
