# Generated by Django 5.2.14 on 2026-05-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_number', models.CharField(max_length=50, unique=True)),
                ('anonymized_voter_hash', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('invalid', 'Invalid')], default='submitted', max_length=20)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('exhausted', 'Exhausted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='elections.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_abstain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.ballot')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.position')),
            ],
            options={
                'ordering': ['position__display_order'],
            },
        ),
        migrations.CreateModel(
            name='VoterParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(default='otp_email', max_length=50)),
                ('ballot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='elections.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='students.student')),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('election', 'student')},
            },
        ),
    ]
